apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: jenkins-docker-springboot
spec:
  selector:
    matchLabels:
      app: jenkins-docker-springboot
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: jenkins-docker-springboot
    spec:
      containers:
        - name: jenkins-docker-springboot
          image: jenkins-docker-springboot:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082 # The port that the container is running on in the cluster